In [1]:
import sys
import numpy as np
import pandas as pd
print('hello world', flush=True)
for i in range(3):
    print(i,flush=True)
print('output on stderr',file=sys.stderr,flush=True)
print('one more on stdout',flush=True)
x = np.arange(10)
print(x)
print(x*2+1)
M=np.random.rand(5,10)  # 5*10 random matrix
u,s,v = np.linalg.svd(M)
print(s)
x=np.random.rand(100) # 100 std normal values
X=np.fft.fft(x)
print(X[:4])   # 4 premieres valeurs
df = pd.DataFrame({'x':[1,2,3],
                  'y':[4,5,6]})# affiche les lignes et les collones avec valeurs
print(df)

hello world
0
1
2


output on stderr


one more on stdout
[0 1 2 3 4 5 6 7 8 9]
[ 1  3  5  7  9 11 13 15 17 19]
[ 3.40876404  1.31664929  1.15024689  0.5279602   0.43736445]
[ 52.41727089+0.j           1.18157128-4.03838766j  -3.47362885+0.656105j
  -2.57317465+0.40245424j]
   x  y
0  1  4
1  2  5
2  3  6
